<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Professor;

class ProfessorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $professors = [
    ["nomeProfessor" => "ABIEL COSTA MACEDO", "instituto" => "IME"],
    ["nomeProfessor" => "ADRIANA ARAUJO CINTRA", "instituto" => "IME"],
    ["nomeProfessor" => "ALACYR JOSE GOMES", "instituto" => "IME"],
    ["nomeProfessor" => "ALINE DE SOUZA LIMA", "instituto" => "IME"],
    ["nomeProfessor" => "ALYSSON TOBIAS RIBEIRO DA CUNHA", "instituto" => "IME"],
    ["nomeProfessor" => "AMANDA BUOSI GAZON MILANI", "instituto" => "IME"],
    ["nomeProfessor" => "ANA PAULA PURCINA BAUMANN", "instituto" => "IME"],
    ["nomeProfessor" => "ANYELLE NOGUEIRA DE SOUZA", "instituto" => "IME"],
    ["nomeProfessor" => "ARMANDO MAURO VASQUEZ CORRO", "instituto" => "IME"],
    ["nomeProfessor" => "BENEDITO LEANDRO NETO", "instituto" => "IME"],
    ["nomeProfessor" => "BRUNO RODRIGUES DE FREITAS", "instituto" => "IME"],
    ["nomeProfessor" => "CYNTHIA ARANTES VIEIRA TOJEIRO", "instituto" => "IME"],
    ["nomeProfessor" => "DAVID HENRIQUES DA MATTA", "instituto" => "IME"],
    ["nomeProfessor" => "DOUGLAS HILARIO DA CRUZ", "instituto" => "IME"],
    ["nomeProfessor" => "DURVAL JOSE TONON", "instituto" => "IME"],
    ["nomeProfessor" => "EDCARLOS DOMINGOS DA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "EDER ANGELO MILANI", "instituto" => "IME"],
    ["nomeProfessor" => "ELISABETH CRISTINA DE FARIA", "instituto" => "IME"],
    ["nomeProfessor" => "EVERTON BATISTA DA ROCHA", "instituto" => "IME"],
    ["nomeProfessor" => "FABIANO FORTUNATO TEIXEIRA DOS SANTOS", "instituto" => "IME"],
    ["nomeProfessor" => "FABIO VITORIANO E SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "GECI JOSE PEREIRA DA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "GLAYDSTON DE CARVALHO BENTO", "instituto" => "IME"],
    ["nomeProfessor" => "GREGORY DURAN CUNHA", "instituto" => "IME"],
    ["nomeProfessor" => "HIURI FELLIPE SANTOS DOS REIS", "instituto" => "IME"],
    ["nomeProfessor" => "HUMBERTO DE ASSIS CLIMACO", "instituto" => "IME"],
    ["nomeProfessor" => "IVONILDES RIBEIRO MARTINS DIAS", "instituto" => "IME"],
    ["nomeProfessor" => "JANICE PEREIRA LOPES", "instituto" => "IME"],
    ["nomeProfessor" => "JAQUELINE ARAUJO CIVARDI", "instituto" => "IME"],
    ["nomeProfessor" => "JEFFERSON DIVINO GONCALVES DE MELO", "instituto" => "IME"],
    ["nomeProfessor" => "JHONE CALDEIRA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "JOELMIR DIVINO CARLOS FELICIANO VILELA", "instituto" => "IME"],
    ["nomeProfessor" => "JOSE HILARIO DA CRUZ", "instituto" => "IME"],
    ["nomeProfessor" => "JOSE PEDRO MACHADO RIBEIRO", "instituto" => "IME"],
    ["nomeProfessor" => "KAMILA DA SILVA ANDRADE", "instituto" => "IME"],
    ["nomeProfessor" => "KARLY BARBOSA ALVARENGA", "instituto" => "IME"],
    ["nomeProfessor" => "KELEM GOMES LOURENCO", "instituto" => "IME"],
    ["nomeProfessor" => "LEANDRO DA FONSECA PRUDENTE", "instituto" => "IME"],
    ["nomeProfessor" => "LEVI ROSA ADRIANO", "instituto" => "IME"],
    ["nomeProfessor" => "LIDIANE DOS SANTOS MONTEIRO LIMA", "instituto" => "IME"],
    ["nomeProfessor" => "LUIS RODRIGO FERNANDES BAUMANN", "instituto" => "IME"],
    ["nomeProfessor" => "LUIS ROMAN LUCAMBIO PEREZ", "instituto" => "IME"],
    ["nomeProfessor" => "LUIZ FERNANDO GONCALVES", "instituto" => "IME"],
    ["nomeProfessor" => "MARCELO ALMEIDA DE SOUZA", "instituto" => "IME"],
    ["nomeProfessor" => "MARCELO BEZERRA BARBOZA", "instituto" => "IME"],
    ["nomeProfessor" => "MARCELO LOPES FERRO", "instituto" => "IME"],
    ["nomeProfessor" => "MARCOS LEANDRO MENDES CARVALHO", "instituto" => "IME"],
    ["nomeProfessor" => "MARIA BETHANIA SARDEIRO DOS SANTOS", "instituto" => "IME"],
    ["nomeProfessor" => "MARIO ERNESTO PISCOYA DIAZ", "instituto" => "IME"],
    ["nomeProfessor" => "MAX LEANDRO NOBRE GONCALVES", "instituto" => "IME"],
    ["nomeProfessor" => "MAX VALERIO LEMES", "instituto" => "IME"],
    ["nomeProfessor" => "MAXWELL LIZETE DA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "MOEMA GOMES MORAES", "instituto" => "IME"],
    ["nomeProfessor" => "OLE PETER SMITH", "instituto" => "IME"],
    ["nomeProfessor" => "ORIZON PEREIRA FERREIRA", "instituto" => "IME"],
    ["nomeProfessor" => "OTAVIO MARCAL LEANDRO GOMIDE", "instituto" => "IME"],
    ["nomeProfessor" => "PAULO HENRIQUE DE AZEVEDO RODRIGUES", "instituto" => "IME"],
    ["nomeProfessor" => "RENATO RODRIGUES SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "RICARDO NUNES DE OLIVEIRA", "instituto" => "IME"],
    ["nomeProfessor" => "RODRIGO DONIZETE EUZEBIO", "instituto" => "IME"],
    ["nomeProfessor" => "ROGERIO DE QUEIROZ CHAVES", "instituto" => "IME"],
    ["nomeProfessor" => "RONALDO ANTONIO DOS SANTOS", "instituto" => "IME"],
    ["nomeProfessor" => "RONY CRISTIANO", "instituto" => "IME"],
    ["nomeProfessor" => "ROSANE GOMES PEREIRA", "instituto" => "IME"],
    ["nomeProfessor" => "ROSANGELA MARIA DA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "TATIANE FERREIRA DO NASCIMENTO MELO DA SILVA", "instituto" => "IME"],
    ["nomeProfessor" => "THAYNARA ARIELLY DE LIMA", "instituto" => "IME"],
    ["nomeProfessor" => "TIAGO MOREIRA VARGAS", "instituto" => "IME"],
    ["nomeProfessor" => "TICIANNE PROENCA BUENO ADORNO", "instituto" => "IME"],
    ["nomeProfessor" => "VALDIVINO VARGAS JUNIOR", "instituto" => "IME"],
    ["nomeProfessor" => "WALTER BATISTA DOS SANTOS", "instituto" => "IME"],
    ["nomeProfessor" => "WELLINGTON LIMA CEDRO", "instituto" => "IME"],
    ["nomeProfessor" => "MAYK JOAQUIM DOS SANTOS", "instituto" => "IME"],
    ["nomeProfessor" => "MILTON JAVIER CARDENAS MENDEZ", "instituto" => "IME"],
    ["nomeProfessor" => "SAMUEL CARLOS DE SOUZA FERREIRA", "instituto" => "IME"],
    ["nomeProfessor" => "STEFFANIO MORENO DE SOUSA", "instituto" => "IME"],   //começo do IF aqui
    ["nomeProfessor" => "ABRAHAM ELIAS ORTEGA PAREDES", "instituto" => "IF"],
    ["nomeProfessor" => "ADOLFO FRANCO JUNIOR", "instituto" => "IF"],
    ["nomeProfessor" => "ANDREIA LUISA DA ROSA", "instituto" => "IF"],
    ["nomeProfessor" => "ANDRIS FIGUEIROA BAKUZIS", "instituto" => "IF"],
    ["nomeProfessor" => "ANTONIO ALONSO", "instituto" => "IF"],
    ["nomeProfessor" => "ARDILEY TORRES AVELAR", "instituto" => "IF"],
    ["nomeProfessor" => "CASSIA ALESSANDRA MARQUEZIN", "instituto" => "IF"],
    ["nomeProfessor" => "CELIA MARIA ALVES DANTAS", "instituto" => "IF"],
    ["nomeProfessor" => "EMERSON NOBUYUKI ITIKAWA", "instituto" => "IF"],
    ["nomeProfessor" => "ERNANNI DAMIAO VIEIRA", "instituto" => "IF"],
    ["nomeProfessor" => "FABIO LUIS BRAGHIN", "instituto" => "IF"],
    ["nomeProfessor" => "FRANCISCO APARECIDO PINTO OSORIO", "instituto" => "IF"],
    ["nomeProfessor" => "GIOVANNI PIACENTE", "instituto" => "IF"],
    ["nomeProfessor" => "GUILHERME COLHERINHAS DE OLIVEIRA", "instituto" => "IF"],
    ["nomeProfessor" => "GUILHERME LUIZ ZANIN", "instituto" => "IF"],
    ["nomeProfessor" => "HERBERT DE CASTRO GEORG", "instituto" => "IF"],
    ["nomeProfessor" => "HERMANN FREIRE FERREIRA LIMA E SILVA", "instituto" => "IF"],
    ["nomeProfessor" => "HERMINIA VERIDIANA DOS SANTOS PESSONI E SILVA", "instituto" => "IF"],
    ["nomeProfessor" => "HUGO JOSE NOGUEIRA PEDROZA DIAS MELLO", "instituto" => "IF"],
    ["nomeProfessor" => "IVO DE ALMEIDA MARQUES", "instituto" => "IF"],
    ["nomeProfessor" => "JEFFERSON ADRIANY RIBEIRO DA CUNHA", "instituto" => "IF"],
    ["nomeProfessor" => "JEFFERSON MARCIO SANCHES LOPES", "instituto" => "IF"],
    ["nomeProfessor" => "JONAS OLIVEIRA DA SILVA", "instituto" => "IF"],
    ["nomeProfessor" => "JOSE RICARDO SABINO", "instituto" => "IF"],
    ["nomeProfessor" => "JOSE RILDO DE OLIVEIRA QUEIROZ", "instituto" => "IF"],
    ["nomeProfessor" => "LADIR CANDIDO DA SILVA", "instituto" => "IF"],
    ["nomeProfessor" => "LAURO JUNE QUEIROZ MAIA", "instituto" => "IF"],
    ["nomeProfessor" => "LEANDRO FELIX DE SOUSA BUFAICAL", "instituto" => "IF"],
    ["nomeProfessor" => "LEANDRO HENRIQUE ZUCOLOTTO COCCA", "instituto" => "IF"],
    ["nomeProfessor" => "LUCAS CHIBEBE CELERI", "instituto" => "IF"],
    ["nomeProfessor" => "LUCIANA CARDOSO MATSUSHIMA", "instituto" => "IF"],
    ["nomeProfessor" => "LUIS MIGUEL GOMES ABEGAO", "instituto" => "IF"],
    ["nomeProfessor" => "LUIZ GONZAGA ROVERSI GENOVESE", "instituto" => "IF"],
    ["nomeProfessor" => "MARCIO ADRIANO RODRIGUES SOUZA", "instituto" => "IF"],
    ["nomeProfessor" => "MARCOS ANTONIO DE CASTRO", "instituto" => "IF"],
    ["nomeProfessor" => "MARCUS CARRIAO DOS SANTOS", "instituto" => "IF"],
    ["nomeProfessor" => "MARIA AMELIA PIRES", "instituto" => "IF"],
    ["nomeProfessor" => "NORTON GOMES DE ALMEIDA", "instituto" => "IF"],
    ["nomeProfessor" => "OSNI SILVA", "instituto" => "IF"],
    ["nomeProfessor" => "PABLO JOSE GONCALVES", "instituto" => "IF"],
    ["nomeProfessor" => "PAULO CELSO FERRARI", "instituto" => "IF"],
    ["nomeProfessor" => "RAFAEL DE MORAIS GOMES", "instituto" => "IF"],
    ["nomeProfessor" => "RENATO BORGES PONTES", "instituto" => "IF"],
    ["nomeProfessor" => "RENATO PESSOA VALE", "instituto" => "IF"],
    ["nomeProfessor" => "RICARDO AVELINO GOMES", "instituto" => "IF"],
    ["nomeProfessor" => "RICARDO COSTA DE SANTANA", "instituto" => "IF"],
    ["nomeProfessor" => "ROMULO CESAR ROUGEMONT PEREIRA", "instituto" => "IF"],
    ["nomeProfessor" => "SALVIANO DE ARAUJO LEAO", "instituto" => "IF"],
    ["nomeProfessor" => "SEBASTIAO ANTONIO MENDANHA NETO", "instituto" => "IF"],
    ["nomeProfessor" => "SILVIO LEAO VIEIRA", "instituto" => "IF"],
    ["nomeProfessor" => "TERTIUS LIMA DA FONSECA", "instituto" => "IF"],
    ["nomeProfessor" => "VANUILDO SILVA DE CARVALHO", "instituto" => "IF"],
    ["nomeProfessor" => "WESLEY BUENO CARDOSO", "instituto" => "IF"],
    ["nomeProfessor" => "FERNANDO MARQUES CARVALHO", "instituto" => "IF"],
    ["nomeProfessor" => "RODRIGO DA SILVA AMORIM", "instituto" => "IF"],
    ["nomeProfessor" => "THIAGO HENRIQUE MOREIRA", "instituto" => "IF"], //inicio do INF
    ["nomeProfessor" => "ADAILTON FERREIRA DE ARAUJO", "instituto" => "INF"],
    ["nomeProfessor" => "ADRIANA SILVEIRA DE SOUZA", "instituto" => "INF"],
    ["nomeProfessor" => "ALDO ANDRE DIAZ SALAZAR", "instituto" => "INF"],
    ["nomeProfessor" => "ALESSANDRO CRUVINEL MACHADO DE ARAUJO", "instituto" => "INF"],
    ["nomeProfessor" => "ANA CLAUDIA BASTOS LOUREIRO MONCAO", "instituto" => "INF"],
    ["nomeProfessor" => "ANDERSON DA SILVA SOARES", "instituto" => "INF"],
    ["nomeProfessor" => "ANDRE LUIZ MOURA", "instituto" => "INF"],
    ["nomeProfessor" => "ANTONIO CARLOS DE OLIVEIRA JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "ARLINDO RODRIGUES GALVAO FILHO", "instituto" => "INF"],
    ["nomeProfessor" => "BRUNO OLIVEIRA SILVESTRE", "instituto" => "INF"],
    ["nomeProfessor" => "CASSIO LEONARDO RODRIGUES", "instituto" => "INF"],
    ["nomeProfessor" => "CEDRIC LUIZ DE CARVALHO", "instituto" => "INF"],
    ["nomeProfessor" => "CELSO GONCALVES CAMILO JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "CRISTIANE BASTOS ROCHA FERREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "DANIEL LIMA VENTURA", "instituto" => "INF"],
    ["nomeProfessor" => "DEBORAH SILVA ALVES FERNANDES", "instituto" => "INF"],
    ["nomeProfessor" => "DELLER JAMES FERREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "DIANE CASTONGUAY", "instituto" => "INF"],
    ["nomeProfessor" => "DIRSON SANTOS DE CAMPOS", "instituto" => "INF"],
    ["nomeProfessor" => "EDISON ANDRADE MARTINS MORAIS", "instituto" => "INF"],
    ["nomeProfessor" => "EDMUNDO SERGIO SPOTO", "instituto" => "INF"],
    ["nomeProfessor" => "EDUARDO SIMOES DE ALBUQUERQUE", "instituto" => "INF"],
    ["nomeProfessor" => "ELIAS BATISTA FERREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "ELIOMAR ARAUJO DE LIMA", "instituto" => "INF"],
    ["nomeProfessor" => "ELISANGELA SILVA DIAS", "instituto" => "INF"],
    ["nomeProfessor" => "ERIKA MORAIS MARTINS COELHO", "instituto" => "INF"],
    ["nomeProfessor" => "EVELLIN CRISTINE SOUZA CARDOSO", "instituto" => "INF"],
    ["nomeProfessor" => "FABIO MOREIRA COSTA", "instituto" => "INF"],
    ["nomeProfessor" => "FABIO NOGUEIRA DE LUCENA", "instituto" => "INF"],
    ["nomeProfessor" => "FABRIZZIO ALPHONSUS ALVES DE MELO NUNES SOARES", "instituto" => "INF"],
    ["nomeProfessor" => "FERNANDO MARQUES FEDERSON", "instituto" => "INF"],
    ["nomeProfessor" => "GILMAR FERREIRA ARANTES", "instituto" => "INF"],
    ["nomeProfessor" => "GUSTAVO TEODORO LAUREANO", "instituto" => "INF"],
    ["nomeProfessor" => "HEBERT COELHO DA SILVA", "instituto" => "INF"],
    ["nomeProfessor" => "HUGO ALEXANDRE DANTAS DO NASCIMENTO", "instituto" => "INF"],
    ["nomeProfessor" => "HUMBERTO JOSE LONGO", "instituto" => "INF"],
    ["nomeProfessor" => "IWENS GERVASIO SENE JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "JACSON RODRIGUES BARBOSA", "instituto" => "INF"],
    ["nomeProfessor" => "JULIANA PEREIRA DE SOUZA ZINADER", "instituto" => "INF"],
    ["nomeProfessor" => "JULIANO LOPES DE OLIVEIRA", "instituto" => "INF"],
    ["nomeProfessor" => "JULLIANO ROSA NASCIMENTO", "instituto" => "INF"],
    ["nomeProfessor" => "KLEBER VIEIRA CARDOSO", "instituto" => "INF"],
    ["nomeProfessor" => "LEIZER DE LIMA PINTO", "instituto" => "INF"],
    ["nomeProfessor" => "LEONARDO ANDRADE RIBEIRO", "instituto" => "INF"],
    ["nomeProfessor" => "LEONARDO ANTONIO ALVES", "instituto" => "INF"],
    ["nomeProfessor" => "LUCAS ARAUJO PEREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "LUCIANA DE OLIVEIRA BERRETTA", "instituto" => "INF"],
    ["nomeProfessor" => "MARCELO AKIRA INUZUKA", "instituto" => "INF"],
    ["nomeProfessor" => "MARCELO RICARDO QUINTA", "instituto" => "INF"],
    ["nomeProfessor" => "MARCIA RODRIGUES CAPPELLE SANTANA", "instituto" => "INF"],
    ["nomeProfessor" => "NADIA FELIX FELIPE DA SILVA", "instituto" => "INF"],
    ["nomeProfessor" => "NIVALDO PEREIRA DE MORAIS JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "OTAVIO CALACA XAVIER", "instituto" => "INF"],
    ["nomeProfessor" => "PLINIO DE SA LEITAO JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "RENATA DUTRA BRAGA", "instituto" => "INF"],
    ["nomeProfessor" => "RENATO DE FREITAS BULCAO NETO", "instituto" => "INF"],
    ["nomeProfessor" => "RICARDO AUGUSTO PEREIRA FRANCO", "instituto" => "INF"],
    ["nomeProfessor" => "ROGERIO LOPES SALVINI", "instituto" => "INF"],
    ["nomeProfessor" => "ROMMEL MELGACO BARBOSA", "instituto" => "INF"],
    ["nomeProfessor" => "RONALDO LOPES DE OLIVEIRA", "instituto" => "INF"],
    ["nomeProfessor" => "RONALDO MARTINS DA COSTA", "instituto" => "INF"],
    ["nomeProfessor" => "RUBENS DE CASTRO PEREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "SAND LUZ CORREA", "instituto" => "INF"],
    ["nomeProfessor" => "SAVIO SALVARINO TELES DE OLIVEIRA", "instituto" => "INF"],
    ["nomeProfessor" => "SERGIO TEIXEIRA DE CARVALHO", "instituto" => "INF"],
    ["nomeProfessor" => "SOFIA LARISSA DA COSTA PAIVA", "instituto" => "INF"],
    ["nomeProfessor" => "TACIANA NOVO KUDO", "instituto" => "INF"],
    ["nomeProfessor" => "TELMA WOERLE DE LIMA SOARES", "instituto" => "INF"],
    ["nomeProfessor" => "THIERSON COUTO ROSA", "instituto" => "INF"],
    ["nomeProfessor" => "VAGNER JOSE DO SACRAMENTO RODRIGUES", "instituto" => "INF"],
    ["nomeProfessor" => "VALDEMAR VICENTE GRACIANO NETO", "instituto" => "INF"],
    ["nomeProfessor" => "VINICIUS DA CUNHA MARTINS BORGES", "instituto" => "INF"],
    ["nomeProfessor" => "VINICIUS SEBBA PATTO", "instituto" => "INF"],
    ["nomeProfessor" => "WANDERLEY DE SOUZA ALENCAR", "instituto" => "INF"],
    ["nomeProfessor" => "WELLINGTON SANTOS MARTINS", "instituto" => "INF"],
    ["nomeProfessor" => "WILLIAM DIVINO FERREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "CARLOS HENRIQUE RORATO SOUZA", "instituto" => "INF"],
    ["nomeProfessor" => "ERNESTO FONSECA VEIGA", "instituto" => "INF"],
    ["nomeProfessor" => "HUGO MARCIANO DE MELO", "instituto" => "INF"],
    ["nomeProfessor" => "LUIZ CARLOS BARBOSA MARTINS", "instituto" => "INF"],
    ["nomeProfessor" => "MARIANA CRISOSTOMO MARTINS", "instituto" => "INF"],
    ["nomeProfessor" => "MATEUS DE PAULA FERREIRA", "instituto" => "INF"],
    ["nomeProfessor" => "MATEUS MACHADO LUNA", "instituto" => "INF"],
    ["nomeProfessor" => "RAPHAEL DOS SANTOS GUEDES VIEIRA", "instituto" => "INF"],
    ["nomeProfessor" => "REINALDO DE SOUZA JUNIOR", "instituto" => "INF"],
    ["nomeProfessor" => "LESLIE RICHARD FOULDS", "instituto" => "INF"], //começo do IQ
    ["nomeProfessor" => "AGUSTINA ROSA ECHEVERRIA", "instituto" => "IQ"],
    ["nomeProfessor" => "ANDREA FERNANDES ARRUDA", "instituto" => "IQ"],
    ["nomeProfessor" => "ANDREA RODRIGUES CHAVES", "instituto" => "IQ"],
    ["nomeProfessor" => "ANNA MARIA CANAVARRO BENITE", "instituto" => "IQ"],
    ["nomeProfessor" => "ANSELMO ELCANA DE OLIVEIRA", "instituto" => "IQ"],
    ["nomeProfessor" => "APARECIDO RIBEIRO DE SOUZA", "instituto" => "IQ"],
    ["nomeProfessor" => "ARACELI APARECIDA SEOLATTO", "instituto" => "IQ"],
    ["nomeProfessor" => "BONIEK GONTIJO VAZ", "instituto" => "IQ"],
    ["nomeProfessor" => "CARIDAD NODA PEREZ", "instituto" => "IQ"],
    ["nomeProfessor" => "CARLOS ALBERTO GALEANO SUAREZ", "instituto" => "IQ"],
    ["nomeProfessor" => "CHRISTIAN GONCALVES ALONSO", "instituto" => "IQ"],
    ["nomeProfessor" => "CLAUDIO ROBERTO MACHADO BENITE", "instituto" => "IQ"],
    ["nomeProfessor" => "DANIELLE CANGUSSU DE CASTRO GOMES", "instituto" => "IQ"],
    ["nomeProfessor" => "DENILSON RABELO", "instituto" => "IQ"],
    ["nomeProfessor" => "DYRNEY ARAUJO DOS SANTOS", "instituto" => "IQ"],
    ["nomeProfessor" => "ELIAS YUKI IONASHIRO", "instituto" => "IQ"],
    ["nomeProfessor" => "EMILIA CELMA DE OLIVEIRA LIMA", "instituto" => "IQ"],
    ["nomeProfessor" => "FABIANO MOLINOS DE ANDRADE", "instituto" => "IQ"],
    ["nomeProfessor" => "FELIPE LANGE COELHO", "instituto" => "IQ"],
    ["nomeProfessor" => "FERNANDA FERREIRA FREITAS", "instituto" => "IQ"],
    ["nomeProfessor" => "FLAVIO COLMATI JUNIOR", "instituto" => "IQ"],
    ["nomeProfessor" => "FREDDY FERNANDES GUIMARAES", "instituto" => "IQ"],
    ["nomeProfessor" => "GABRIELA RODRIGUES MENDES DUARTE", "instituto" => "IQ"],
    ["nomeProfessor" => "INDIANARA CONCEICAO OSTROSKI", "instituto" => "IQ"],
    ["nomeProfessor" => "INTI DORACI CAVALCANTI MONTANO", "instituto" => "IQ"],
    ["nomeProfessor" => "JUVENAL CAROLINO DA SILVA FILHO", "instituto" => "IQ"],
    ["nomeProfessor" => "LEONILDO ALVES FERREIRA", "instituto" => "IQ"],
    ["nomeProfessor" => "LILIANE MAGALHAES NUNES", "instituto" => "IQ"],
    ["nomeProfessor" => "LIVIA FLORIO SGOBBI", "instituto" => "IQ"],
    ["nomeProfessor" => "LUCIANO MORAIS LIAO", "instituto" => "IQ"],
    ["nomeProfessor" => "LUCILIA KATO", "instituto" => "IQ"],
    ["nomeProfessor" => "LUIZ HENRIQUE KENG QUEIROZ JUNIOR", "instituto" => "IQ"],
    ["nomeProfessor" => "MARGARETE MARTINS PEREIRA FERREIRA", "instituto" => "IQ"],
    ["nomeProfessor" => "MARIA INES GONCALVES LELES", "instituto" => "IQ"],
    ["nomeProfessor" => "MARIA ISABEL RIBEIRO ALVES", "instituto" => "IQ"],
    ["nomeProfessor" => "MARLON HERBERT FLORA BARBOSA SOARES", "instituto" => "IQ"],
    ["nomeProfessor" => "MARTIN SCHWELLBERGER BARBOSA", "instituto" => "IQ"],
    ["nomeProfessor" => "NELSON ROBERTO ANTONIOSI FILHO", "instituto" => "IQ"],
    ["nomeProfessor" => "NEUCIRIO RICARDO DE AZEVEDO", "instituto" => "IQ"],
    ["nomeProfessor" => "NUBIA NATALIA DE BRITO", "instituto" => "IQ"],
    ["nomeProfessor" => "NYUARA ARAUJO DA SILVA MESQUITA", "instituto" => "IQ"],
    ["nomeProfessor" => "OLGA SOARES DO REGO BARROS", "instituto" => "IQ"],
    ["nomeProfessor" => "PATRICIA POMME CONFESSORI SARTORATTO", "instituto" => "IQ"],
    ["nomeProfessor" => "PAULO ROBERTO MARTINS", "instituto" => "IQ"],
    ["nomeProfessor" => "PAULO SERGIO DE SOUZA", "instituto" => "IQ"],
    ["nomeProfessor" => "PEDRO HENRIQUE FERRI", "instituto" => "IQ"],
    ["nomeProfessor" => "RAFAEL MACEDO DIAS", "instituto" => "IQ"],
    ["nomeProfessor" => "RAFAEL PAVAO DAS CHAGAS", "instituto" => "IQ"],
    ["nomeProfessor" => "SUMBAL SABA", "instituto" => "IQ"],
    ["nomeProfessor" => "SUZANA DA COSTA SANTOS", "instituto" => "IQ"],
    ["nomeProfessor" => "TATIANA DUQUE MARTINS ERTNER DE ALMEIDA", "instituto" => "IQ"],
    ["nomeProfessor" => "THIAGO LEANDRO DE SOUZA", "instituto" => "IQ"],
    ["nomeProfessor" => "VANESSA GISELE PASQUALOTTO SEVERINO", "instituto" => "IQ"],
    ["nomeProfessor" => "WENDELL KARLOS TOMAZELLI COLTRO", "instituto" => "IQ"],
    ["nomeProfessor" => "HEIBBE CRISTHIAN BENEDITO DE OLIVEIRA", "instituto" => "IQ"],
    ["nomeProfessor" => "FLAVIO OLIMPIO SANCHES NETO", "instituto" => "IQ"],
    ["nomeProfessor" => "MATEUS RODRIGUES BARBOSA", "instituto" => "IQ"],
    ["nomeProfessor" => "RENATO RABELO DE SOUZA FILHO", "instituto" => "IQ"],
    ["nomeProfessor" => "MUHAMMAD IRFAN QADIR", "instituto" => "IQ"], // começo do EMC
    ["nomeProfessor" => "ADEMYR GONCALVES DE OLIVEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "ADRIANO CESAR SANTANA", "instituto" => "EMC"],
    ["nomeProfessor" => "ALISSON ASSIS CARDOSO", "instituto" => "EMC"],
    ["nomeProfessor" => "AMANDA ALBERTIN XAVIER DA SILVA", "instituto" => "EMC"],
    ["nomeProfessor" => "ANA CLAUDIA MARQUES DO VALLE", "instituto" => "EMC"],
    ["nomeProfessor" => "ANDREIA AOYAGUI NASCIMENTO", "instituto" => "EMC"],
    ["nomeProfessor" => "ANTONIO MELO DE OLIVEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "BERNARDO PINHEIRO DE ALVARENGA", "instituto" => "EMC"],
    ["nomeProfessor" => "CACILDA DE JESUS RIBEIRO", "instituto" => "EMC"],
    ["nomeProfessor" => "CARLOS ALBERTO DE ALMEIDA VILELA", "instituto" => "EMC"],
    ["nomeProfessor" => "CARLOS GALVAO PINHEIRO JUNIOR", "instituto" => "EMC"],
    ["nomeProfessor" => "CASSIO DENER NORONHA VINHAL", "instituto" => "EMC"],
    ["nomeProfessor" => "DANIEL FERNANDES DA CUNHA", "instituto" => "EMC"],
    ["nomeProfessor" => "DANIEL SOUZA", "instituto" => "EMC"],
    ["nomeProfessor" => "DEMOSTENES FERREIRA FILHO", "instituto" => "EMC"],
    ["nomeProfessor" => "EMILSON ROCHA DE OLIVEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "ENES GONCALVES MARRA", "instituto" => "EMC"],
    ["nomeProfessor" => "FELIPE PAMPLONA MARIANO", "instituto" => "EMC"],
    ["nomeProfessor" => "FERNANDO FERREIRA DE MELO", "instituto" => "EMC"],
    ["nomeProfessor" => "FLAVIO GERALDO COELHO ROCHA", "instituto" => "EMC"],
    ["nomeProfessor" => "FLAVIO HENRIQUE TELES VIEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "GELSON ANTONIO ANDREA BRIGATTO", "instituto" => "EMC"],
    ["nomeProfessor" => "GELSON DA CRUZ JUNIOR", "instituto" => "EMC"],
    ["nomeProfessor" => "GETULIO ANTERO DE DEUS JUNIOR", "instituto" => "EMC"],
    ["nomeProfessor" => "GEYVERSON TEIXEIRA DE PAULA", "instituto" => "EMC"],
    ["nomeProfessor" => "GINO BERTOLLUCCI COLHERINHAS", "instituto" => "EMC"],
    ["nomeProfessor" => "IGOR KOPCAK", "instituto" => "EMC"],
    ["nomeProfessor" => "JOAO PAULO DA SILVA FONSECA", "instituto" => "EMC"],
    ["nomeProfessor" => "JOSE WILSON LIMA NERYS", "instituto" => "EMC"],
    ["nomeProfessor" => "KARINA ROCHA GOMES DA SILVA", "instituto" => "EMC"],
    ["nomeProfessor" => "KLEBER MENDES DE FIGUEIREDO", "instituto" => "EMC"],
    ["nomeProfessor" => "LEONARDO DA CUNHA BRITO", "instituto" => "EMC"],
    ["nomeProfessor" => "LEONARDO DE QUEIROZ MOREIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "LEONARDO GUERRA DE REZENDE GUEDES", "instituto" => "EMC"],
    ["nomeProfessor" => "LINA PAOLA GARCES NEGRETE", "instituto" => "EMC"],
    ["nomeProfessor" => "LOURENCO MATIAS", "instituto" => "EMC"],
    ["nomeProfessor" => "MARA GRACE SILVA FIGUEIREDO", "instituto" => "EMC"],
    ["nomeProfessor" => "MARCELO STEHLING DE CASTRO", "instituto" => "EMC"],
    ["nomeProfessor" => "MARCO ANTONIO ASSFALK DE OLIVEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "MARCOS ANTONIO DE SOUSA", "instituto" => "EMC"],
    ["nomeProfessor" => "MARIA LEONOR SILVA DE ALMEIDA", "instituto" => "EMC"],
    ["nomeProfessor" => "MARLIPE GARCIA FAGUNDES NETO", "instituto" => "EMC"],
    ["nomeProfessor" => "REINALDO GONCALVES NOGUEIRA", "instituto" => "EMC"],
    ["nomeProfessor" => "RODRIGO PINTO LEMOS", "instituto" => "EMC"],
    ["nomeProfessor" => "SANDRERLEY RAMOS PIRES", "instituto" => "EMC"],
    ["nomeProfessor" => "SERGIO ARAUJO DE FIGUEIREDO", "instituto" => "EMC"],
    ["nomeProfessor" => "SERGIO GRANATO DE ARAUJO", "instituto" => "EMC"],
    ["nomeProfessor" => "SERGIO PIRES PIMENTEL", "instituto" => "EMC"],
    ["nomeProfessor" => "SIGEO KITATANI JUNIOR", "instituto" => "EMC"],
    ["nomeProfessor" => "THYAGO CARVALHO MARQUES", "instituto" => "EMC"],
    ["nomeProfessor" => "TOMAS ANTONIO COSTA BADAN", "instituto" => "EMC"],
    ["nomeProfessor" => "WANDER GONCALVES DA SILVA", "instituto" => "EMC"],
    ["nomeProfessor" => "WANIR JOSE DE MEDEIROS JUNIOR", "instituto" => "EMC"],
    ["nomeProfessor" => "WEBER MARTINS", "instituto" => "EMC"],
    ["nomeProfessor" => "MARCOS LEMOS AFONSO", "instituto" => "EMC"],
    ["nomeProfessor" => "LUIZ HENRIQUE REIS DE JESUS", "instituto" => "EMC"], //começo da FACE
    ["nomeProfessor" => "ADRIANA FERREIRA SILVA", "instituto" => "FACE"],
    ["nomeProfessor" => "ALETHEIA FERREIRA DA CRUZ", "instituto" => "FACE"],
    ["nomeProfessor" => "ANDERSON MUTTER TEIXEIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "ANDREA FREIRE DE LUCENA", "instituto" => "FACE"],
    ["nomeProfessor" => "ANTONIO MARCOS DE QUEIROZ", "instituto" => "FACE"],
    ["nomeProfessor" => "CAMILA ARAUJO MACHADO", "instituto" => "FACE"],
    ["nomeProfessor" => "CANDIDO VIEIRA BORGES JUNIOR", "instituto" => "FACE"],
    ["nomeProfessor" => "CARLOS HENRIQUE SILVA DO CARMO", "instituto" => "FACE"],
    ["nomeProfessor" => "CELMA DUQUE FERREIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "CLAUDIA REGINA ROSAL CARVALHO", "instituto" => "FACE"],
    ["nomeProfessor" => "CLEIDINALDO DE JESUS BARBOSA", "instituto" => "FACE"],
    ["nomeProfessor" => "CLEYZER ADRIAN DA CUNHA", "instituto" => "FACE"],
    ["nomeProfessor" => "DAIANA PAULA PIMENTA", "instituto" => "FACE"],
    ["nomeProfessor" => "DANIELA ROSIM", "instituto" => "FACE"],
    ["nomeProfessor" => "DERMEVAL MARTINS BORGES JUNIOR", "instituto" => "FACE"],
    ["nomeProfessor" => "EDNEI MORAIS PEREIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "EDSON ROBERTO VIEIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "EDWARD HUMBERTO GUIMARAES JUNIOR", "instituto" => "FACE"],
    ["nomeProfessor" => "EMERSON SANTANA DE SOUZA", "instituto" => "FACE"],
    ["nomeProfessor" => "ERCILIO ZANOLLA", "instituto" => "FACE"],
    ["nomeProfessor" => "ESTELA NAJBERG", "instituto" => "FACE"],
    ["nomeProfessor" => "EVERTON SOTTO TIBIRICA ROSA", "instituto" => "FACE"],
    ["nomeProfessor" => "FELIPE NOGUEIRA DA CRUZ", "instituto" => "FACE"],
    ["nomeProfessor" => "FELIPE QUEIROZ SILVA", "instituto" => "FACE"],
    ["nomeProfessor" => "FLAVIA REZENDE CAMPOS", "instituto" => "FACE"],
    ["nomeProfessor" => "FRANCISCO BRUNO DE LIMA HOLANDA", "instituto" => "FACE"],
    ["nomeProfessor" => "GILBERTO CRISPIM DA SILVA", "instituto" => "FACE"],
    ["nomeProfessor" => "ILIRIO JOSE RECH", "instituto" => "FACE"],
    ["nomeProfessor" => "JÉSSICA TRAGUETTO SILVA", "instituto" => "FACE"],
    ["nomeProfessor" => "JOHNNY JORGE DE OLIVEIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "JULIANO LIMA SOARES", "instituto" => "FACE"],
    ["nomeProfessor" => "JULIO ORESTES DA SILVA", "instituto" => "FACE"],
    ["nomeProfessor" => "KLEBER DOMINGOS DE ARAUJO", "instituto" => "FACE"],
    ["nomeProfessor" => "LARISSA BARBOSA CARDOSO", "instituto" => "FACE"],
    ["nomeProfessor" => "LUCIO DE SOUZA MACHADO", "instituto" => "FACE"],
    ["nomeProfessor" => "MAC DAVES DE MORAIS FREIRE", "instituto" => "FACE"],
    ["nomeProfessor" => "MARCELO FERREIRA TETE", "instituto" => "FACE"],
    ["nomeProfessor" => "MARCOS INACIO SEVERO DE ALMEIDA", "instituto" => "FACE"],
    ["nomeProfessor" => "MARIA SALETE BATISTA FREITAG", "instituto" => "FACE"],
    ["nomeProfessor" => "MICHELE RILANY RODRIGUES MACHADO", "instituto" => "FACE"],
    ["nomeProfessor" => "MIGUEL ANGELO DE FRANCA COSTA", "instituto" => "FACE"],
    ["nomeProfessor" => "MOISES FERREIRA DA CUNHA", "instituto" => "FACE"],
    ["nomeProfessor" => "PAULA ANDREA DO VALLE HAMBERGER", "instituto" => "FACE"],
    ["nomeProfessor" => "PEDRO HENRIQUE EVANGELISTA DUARTE", "instituto" => "FACE"],
    ["nomeProfessor" => "RICARDO LIMONGI FRANCA COELHO", "instituto" => "FACE"],
    ["nomeProfessor" => "RICARDO MESSIAS ROSSI", "instituto" => "FACE"],
    ["nomeProfessor" => "SANDRO EDUARDO MONSUETO", "instituto" => "FACE"],
    ["nomeProfessor" => "SERGIO FORNAZIER MEYRELLES FILHO", "instituto" => "FACE"],
    ["nomeProfessor" => "SERGIO HENRIQUE BARROCA COSTA", "instituto" => "FACE"],
    ["nomeProfessor" => "TATIANE BENTO DA COSTA", "instituto" => "FACE"],
    ["nomeProfessor" => "THIAGO ALVES", "instituto" => "FACE"],
    ["nomeProfessor" => "THIAGO CAVALCANTE DE SOUZA", "instituto" => "FACE"],
    ["nomeProfessor" => "TIAGO CAMARINHA LOPES", "instituto" => "FACE"],
    ["nomeProfessor" => "VITORIA AUGUSTA BRAGA DE SOUZA", "instituto" => "FACE"],
    ["nomeProfessor" => "WALDEMIRO ALCANTARA DA SILVA NETO", "instituto" => "FACE"],
    ["nomeProfessor" => "PAULO ROBERTO SCALCO", "instituto" => "FACE"],
    ["nomeProfessor" => "ADRIANA MOURA GUIMARAES", "instituto" => "FACE"],
    ["nomeProfessor" => "ANA LUIZA SOUZA MENDES", "instituto" => "FACE"],
    ["nomeProfessor" => "CESAR CINTRA FREITAS SIGNATES", "instituto" => "FACE"],
    ["nomeProfessor" => "GABRIELA ARAUJO ROMAO", "instituto" => "FACE"],
    ["nomeProfessor" => "MARILIA PARANAIBA FERREIRA", "instituto" => "FACE"],
    ["nomeProfessor" => "MICHELE APARECIDA CUNHA", "instituto" => "FACE"],
    ["nomeProfessor" => "PAULO JUNIO PEREIRA DE MOURA", "instituto" => "FACE"], // começo do EECA
    ["nomeProfessor" => "ADEMIR APARECIDO DO PRADO", "instituto" => "EECA"],
    ["nomeProfessor" => "ALBERTO VILELA CHAER", "instituto" => "EECA"],
    ["nomeProfessor" => "ANDRE LUIZ BORTOLAZ GEYER", "instituto" => "EECA"],
    ["nomeProfessor" => "ANDRIELLI MORAIS DE OLIVEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "ARIOVALDO FERNANDES DE ALMEIDA", "instituto" => "EECA"],
    ["nomeProfessor" => "ARTHUR ALAX DE ARAUJO ALBUQUERQUE", "instituto" => "EECA"],
    ["nomeProfessor" => "CARLOS ALBERTO LAURO VARGAS", "instituto" => "EECA"],
    ["nomeProfessor" => "DANIEL DE LIMA ARAUJO", "instituto" => "EECA"],
    ["nomeProfessor" => "DANILO DUARTE COSTA E SILVA", "instituto" => "EECA"],
    ["nomeProfessor" => "DARIO QUEIJA DE SIQUEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "DENILSON TEIXEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "EDER CARLOS GUEDES DOS SANTOS", "instituto" => "EECA"],
    ["nomeProfessor" => "EDGAR BACARJI", "instituto" => "EECA"],
    ["nomeProfessor" => "EMILIANO LOBO DE GODOI", "instituto" => "EECA"],
    ["nomeProfessor" => "ENIO JOSE PAZINI FIGUEIREDO", "instituto" => "EECA"],
    ["nomeProfessor" => "ERALDO HENRIQUES DE CARVALHO", "instituto" => "EECA"],
    ["nomeProfessor" => "FRANCISCO JAVIER CUBA TERAN", "instituto" => "EECA"],
    ["nomeProfessor" => "FREDERICO MARTINS ALVES DA SILVA", "instituto" => "EECA"],
    ["nomeProfessor" => "GILSON DE FARIAS NEVES GITIRANA JUNIOR", "instituto" => "EECA"],
    ["nomeProfessor" => "GIOVANA CARLA ELIAS FLEURY", "instituto" => "EECA"],
    ["nomeProfessor" => "HUGO JOSE RIBEIRO", "instituto" => "EECA"],
    ["nomeProfessor" => "HUMBERTO CARLOS RUGGERI JUNIOR", "instituto" => "EECA"],
    ["nomeProfessor" => "JANES CLEITON ALVES DE OLIVEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "JOEL ROBERTO GUIMARAES VASCO", "instituto" => "EECA"],
    ["nomeProfessor" => "JOSE VICENTE GRANATO DE ARAUJO", "instituto" => "EECA"],
    ["nomeProfessor" => "JULIANA DORN NOBREGA", "instituto" => "EECA"],
    ["nomeProfessor" => "KAIO CESAR BORGES BENEDETTI", "instituto" => "EECA"],
    ["nomeProfessor" => "KARLA ALCIONE DA SILVA CRUVINEL", "instituto" => "EECA"],
    ["nomeProfessor" => "KARLA EMMANUELA RIBEIRO HORA", "instituto" => "EECA"],
    ["nomeProfessor" => "KATIA ALCIONE KOPP", "instituto" => "EECA"],
    ["nomeProfessor" => "KLEBBER TEODOMIRO MARTINS FORMIGA", "instituto" => "EECA"],
    ["nomeProfessor" => "LAIS ROBERTA GALDINO DE OLIVEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "LILIAN RIBEIRO DE REZENDE", "instituto" => "EECA"],
    ["nomeProfessor" => "LORENA DA SILVA ALVES", "instituto" => "EECA"],
    ["nomeProfessor" => "MARCIA MARIA DOS ANJOS MASCARENHA", "instituto" => "EECA"],
    ["nomeProfessor" => "MARCIO BELLUOMINI MORAES", "instituto" => "EECA"],
    ["nomeProfessor" => "MARCUS ANDRE SIQUEIRA CAMPOS", "instituto" => "EECA"],
    ["nomeProfessor" => "MARIA CAROLINA GOMES DE OLIVEIRA BRANDSTETTER", "instituto" => "EECA"],
    ["nomeProfessor" => "MAURICIO MARTINES SALES", "instituto" => "EECA"],
    ["nomeProfessor" => "NILSON CLEMENTINO FERREIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "NORA KATIA SAAVEDRA DEL AGUILA HOFFMANN", "instituto" => "EECA"],
    ["nomeProfessor" => "OSWALDO CASCUDO MATOS", "instituto" => "EECA"],
    ["nomeProfessor" => "PAULO SERGIO SCALIZE", "instituto" => "EECA"],
    ["nomeProfessor" => "RAVIEL EURICO BASSO", "instituto" => "EECA"],
    ["nomeProfessor" => "RENATA MACHADO SOARES", "instituto" => "EECA"],
    ["nomeProfessor" => "RENATA MEDICI FRAYNE CUBA", "instituto" => "EECA"],
    ["nomeProfessor" => "RENATO RESENDE ANGELIM", "instituto" => "EECA"],
    ["nomeProfessor" => "RICARDO PRADO ABREU REIS", "instituto" => "EECA"],
    ["nomeProfessor" => "SAULO BRUNO SILVEIRA E SOUZA", "instituto" => "EECA"],
    ["nomeProfessor" => "SIMONE COSTA PFEIFFER", "instituto" => "EECA"],
    ["nomeProfessor" => "TATIANA GONDIM DO AMARAL", "instituto" => "EECA"],
    ["nomeProfessor" => "TULE CESAR BARCELOS MAIA", "instituto" => "EECA"],
    ["nomeProfessor" => "ULISSES GUIMARAES ULHOA", "instituto" => "EECA"],
    ["nomeProfessor" => "WELLINGTON NUNES DE OLIVEIRA", "instituto" => "EECA"],
    ["nomeProfessor" => "ZENON JOSE GUZMAN DEL PRADO", "instituto" => "EECA"],
    ["nomeProfessor" => "CECILE GUIMARAES ULHOA", "instituto" => "EECA"]
        ];

        foreach ($professors as $professor) {
            Professor::create([
                'nomeProfessor' => $professor['nomeProfessor'],
                'instituto' => $professor['instituto'],
                'Nota' => 0,
                'QtsAvalicao'=>0,
                'QtsN1'=>0,
                'QtsN2'=>0,
                'QtsN3'=>0,
                'QtsN4'=>0,
                'QtsN5'=>0,
                'QtsN6'=>0,
                'QtsN7'=>0,
                'QtsN8'=>0,
                'QtsN9'=>0,
                'QtsN10'=>0
            ]);
        }
    }
}
